// Strayaword answer list — 5-letter Australian slang / colloquial words.
// Each is a genuinely used Aussie term. Definitions are plain-English summaries.
// Family-friendly; nothing here is stronger than "bugga".

export interface SlangWord {
  word: string; // 5 uppercase letters
  meaning: string;
  example: string;
}

export const ANSWERS: SlangWord[] = [
  { word: 'BOGAN', meaning: 'An unsophisticated or unfashionable person — often said with a bit of affection.', example: '“He’s a bit of a bogan, but a good bloke.”' },
  { word: 'SERVO', meaning: 'A service station / petrol station.', example: '“Grab some milk from the servo on the way home.”' },
  { word: 'DUNNY', meaning: 'A toilet, especially an outside one.', example: '“The dunny’s round the back.”' },
  { word: 'CHOOK', meaning: 'A chicken.', example: '“Bought a hot chook for dinner.”' },
  { word: 'SANGA', meaning: 'A sandwich.', example: '“Just a cheese and tomato sanga for me.”' },
  { word: 'SNAGS', meaning: 'Sausages.', example: '“Chuck the snags on the barbie.”' },
  { word: 'DAGGY', meaning: 'Unfashionable or uncool, usually affectionately.', example: '“That’s a daggy old jumper.”' },
  { word: 'CROOK', meaning: 'Unwell, or broken / not working.', example: '“I’m feeling a bit crook today.”' },
  { word: 'YAKKA', meaning: 'Hard work.', example: '“Digging that trench was hard yakka.”' },
  { word: 'BONZA', meaning: 'Excellent, great.', example: '“What a bonza day for the beach.”' },
  { word: 'TINNY', meaning: 'A can of beer; also a small aluminium boat; also lucky.', example: '“Pass us a tinny from the esky.”' },
  { word: 'BLOKE', meaning: 'A man.', example: '“He’s a decent sort of bloke.”' },
  { word: 'BLUEY', meaning: 'A nickname for a redhead; also a blue heeler dog.', example: '“Oi, Bluey, over here!”' },
  { word: 'RANGA', meaning: 'A person with red hair (from “orangutan”).', example: '“Us rangas need extra sunscreen.”' },
  { word: 'GALAH', meaning: 'A foolish person (also the pink-and-grey cockatoo).', example: '“Stop carrying on like a galah.”' },
  { word: 'YOBBO', meaning: 'A loud, uncouth, badly behaved person.', example: '“A carload of yobbos went past yelling.”' },
  { word: 'OCKER', meaning: 'A rough, stereotypically Australian bloke or manner of speaking.', example: '“He puts on a real ocker accent for tourists.”' },
  { word: 'CUPPA', meaning: 'A cup of tea or coffee.', example: '“Sit down and I’ll make you a cuppa.”' },
  { word: 'MOOLA', meaning: 'Money.', example: '“Made a bit of moola on the side.”' },
  { word: 'PLONK', meaning: 'Cheap wine.', example: '“Just bring a bottle of plonk.”' },
  { word: 'BILLY', meaning: 'A tin used to boil water for tea over a campfire.', example: '“Chuck the billy on, I’m gasping for a cuppa.”' },
  { word: 'AMPED', meaning: 'Excited and full of energy.', example: '“I’m amped for the game tonight.”' },
  { word: 'SHOUT', meaning: 'Your turn to buy a round of drinks.', example: '“Put your wallet away — it’s my shout.”' },
  { word: 'SCULL', meaning: 'To drink a whole drink without stopping.', example: '“Scull, scull, scull!”' },
  { word: 'CHUCK', meaning: 'To throw, or to do (chuck a sickie, chuck a U-ey).', example: '“Chuck us the sunscreen.”' },
  { word: 'RORTS', meaning: 'Scams or rip-offs, often involving public money.', example: '“Another travel expenses rort.”' },
  { word: 'DODGY', meaning: 'Unreliable, suspect or dishonest.', example: '“The brakes feel a bit dodgy.”' },
  { word: 'BODGY', meaning: 'Badly made; of poor quality.', example: '“A bodgy paint job.”' },
  { word: 'FERAL', meaning: 'Wild, filthy, or completely out of control.', example: '“The party went totally feral.”' },
  { word: 'PORKY', meaning: 'A lie (from “porky pie”).', example: '“Don’t tell porkies.”' },
  { word: 'SOOKY', meaning: 'Inclined to sulk or cry easily.', example: '“Don’t be sooky about it.”' },
  { word: 'BOOFY', meaning: 'Big and muscular but not too bright.', example: '“A boofy front-rower.”' },
  { word: 'SPUNK', meaning: 'A very attractive person.', example: '“Your new neighbour is a total spunk.”' },
  { word: 'FIRIE', meaning: 'A firefighter.', example: '“Her sister’s a firie in the CFA.”' },
  { word: 'POKIE', meaning: 'A poker machine.', example: '“Dropped fifty bucks on the pokies.”' },
  { word: 'DEVON', meaning: 'A bland processed luncheon meat.', example: '“Devon and dead horse on white bread.”' },
  { word: 'DACKS', meaning: 'Trousers or pants.', example: '“Put your trackie dacks on.”' },
  { word: 'FROTH', meaning: 'To be extremely excited or keen.', example: '“Frothing for the long weekend.”' },
  { word: 'HEAPS', meaning: 'A lot; very.', example: '“Thanks heaps.” / “He’s heaps better now.”' },
  { word: 'LOLLY', meaning: 'A sweet / piece of candy; also “do your lolly” = lose your temper.', example: '“Grab a bag of lollies for the trip.”' },
  { word: 'BEAUT', meaning: 'Great, excellent (short for beautiful).', example: '“She’ll be a beaut day tomorrow.”' },
  { word: 'GUNNA', meaning: 'Someone who is always “gunna” do something but never does.', example: '“He’s all talk — a real gunna.”' },
  { word: 'SKITE', meaning: 'To boast; a person who brags.', example: '“Stop skiting about your new car.”' },
  { word: 'STIFF', meaning: 'Unlucky.', example: '“Missed out by one point — stiff luck, mate.”' },
  { word: 'AGGRO', meaning: 'Aggressive, or aggression / hassle.', example: '“No need to get all aggro.”' },
  { word: 'LAIRY', meaning: 'Flashy, loud or garish.', example: '“A lairy Hawaiian shirt.”' },
  { word: 'PIKER', meaning: 'Someone who backs out or heads home early.', example: '“Don’t be a piker, stay for one more.”' },
  { word: 'SPRAY', meaning: 'A loud telling-off.', example: '“The coach gave them a spray at half-time.”' },
  { word: 'STINK', meaning: 'A fight, or a big fuss.', example: '“There was a bit of a stink at the pub.”' },
  { word: 'PRANG', meaning: 'A minor car crash.', example: '“Had a little prang in the car park.”' },
  { word: 'GRUNT', meaning: 'Power, especially of an engine.', example: '“This ute’s got a bit of grunt.”' },
  { word: 'CHEWY', meaning: 'Chewing gum; also a footy heckle (“chewy on ya boot”).', example: '“Anyone got some chewy?”' },
  { word: 'NANNA', meaning: 'Grandmother; also “nanna nap” = an afternoon sleep.', example: '“Might have a quick nanna nap.”' },
  { word: 'POPPY', meaning: 'As in “tall poppy” — someone successful who gets cut down.', example: '“Classic tall poppy syndrome.”' },
  { word: 'MUFTI', meaning: 'Casual clothes instead of a uniform (mufti day at school).', example: '“It’s mufti day, bring a gold coin.”' },
  { word: 'BUGGA', meaning: 'A mild expression of annoyance; also “poor bugga” = poor thing.', example: '“Bugga, forgot my keys.”' },
  { word: 'NUFFY', meaning: 'A fool or idiot.', example: '“Ya bloody nuffy.”' },
  { word: 'CHAMP', meaning: 'A friendly (sometimes sarcastic) term of address.', example: '“Good on ya, champ.”' },
  { word: 'REGGO', meaning: 'Vehicle registration (also spelled rego).', example: '“The reggo’s due next month.”' },
  { word: 'SEEYA', meaning: 'Casual goodbye.', example: '“Seeya this arvo.”' },
  { word: 'MANKY', meaning: 'Dirty, grubby or unpleasant.', example: '“Manky old thongs by the back door.”' },
  { word: 'NUDDY', meaning: 'Naked (“in the nuddy”).', example: '“Kids ran through the sprinkler in the nuddy.”' },
  { word: 'WALLY', meaning: 'A harmless fool.', example: '“I felt like a right wally.”' },
  { word: 'GOOSE', meaning: 'A silly person.', example: '“Ya big goose.”' },
  { word: 'GROGS', meaning: 'Alcoholic drinks (grog = alcohol).', example: '“Who’s on the grogs run?”' },
  { word: 'DILLY', meaning: 'Silly or foolish; also a “dilly bag”.', example: '“Don’t be dilly.”' },
  { word: 'LURKS', meaning: 'Perks or dodges of a job (“lurks and perks”).', example: '“He knows all the lurks.”' },
  { word: 'DEKKO', meaning: 'A quick look.', example: '“Have a dekko at this.”' },
  { word: 'STROP', meaning: 'A bad mood or sulk (“in a strop”).', example: '“He spat the dummy and went off in a strop.”' },
  { word: 'CACKY', meaning: 'No good; poor quality; a drab brownish colour.', example: '“The wi-fi out here is cacky.”' },
];

// Extra slang for the on-page glossary (SEO). Not used as puzzle answers.
export const GLOSSARY: { term: string; meaning: string }[] = [
  { term: 'Arvo', meaning: 'Afternoon.' },
  { term: 'Barbie', meaning: 'Barbecue.' },
  { term: 'Bikkie', meaning: 'Biscuit; “cost big bikkies” = expensive.' },
  { term: 'Bottle-o', meaning: 'Bottle shop / liquor store.' },
  { term: 'Brekkie', meaning: 'Breakfast.' },
  { term: 'Bludger', meaning: 'A lazy person who avoids work.' },
  { term: 'Chrissie', meaning: 'Christmas.' },
  { term: 'Crikey', meaning: 'Exclamation of surprise.' },
  { term: 'Dead horse', meaning: 'Tomato sauce (rhyming slang).' },
  { term: 'Dinkum / fair dinkum', meaning: 'Genuine, true, honest.' },
  { term: 'Doona', meaning: 'A quilt or duvet.' },
  { term: 'Drongo', meaning: 'A slow-witted or foolish person.' },
  { term: 'Esky', meaning: 'A portable cooler / ice box.' },
  { term: 'Exy', meaning: 'Expensive.' },
  { term: 'Grommet / grom', meaning: 'A young surfer or skater.' },
  { term: 'Hooroo', meaning: 'Goodbye.' },
  { term: 'Larrikin', meaning: 'A mischievous, cheeky person.' },
  { term: 'Maccas', meaning: "McDonald's." },
  { term: 'Mozzie', meaning: 'Mosquito.' },
  { term: 'No worries', meaning: '“It’s fine” / “you’re welcome”.' },
  { term: 'Ripper', meaning: 'Excellent, fantastic.' },
  { term: 'Rock up', meaning: 'To arrive / turn up.' },
  { term: "She'll be right", meaning: 'It will be OK.' },
  { term: 'Sickie', meaning: 'A day off work claiming illness.' },
  { term: 'Snag', meaning: 'A sausage.' },
  { term: 'Sparky', meaning: 'An electrician.' },
  { term: 'Stubby', meaning: 'A small (375 ml) beer bottle.' },
  { term: 'Sunnies', meaning: 'Sunglasses.' },
  { term: 'Thongs', meaning: 'Flip-flops / rubber sandals.' },
  { term: 'Tradie', meaning: 'A tradesperson (electrician, plumber, etc.).' },
  { term: 'Ute', meaning: 'A utility vehicle / pickup truck.' },
  { term: 'Woop Woop', meaning: 'A remote, far-away place.' },
  { term: 'Yonks', meaning: 'A long time.' },
];
